openapi: 3.0.3
info:
  description: TH1
  title: TH1
  version: 0.0.1

paths:
  /converter:
    post:
      operationId: convertTable
      parameters:
        - in: query
          name: mode
          required: false
          schema:
            $ref: '#/components/schemas/dataInsertionMode'
      responses:
        "200":
          description: OK

components:
  schemas:
    dataInsertionMode:
      type: string
      enum:
        - CREATE
        - EXTEND
        - REPLACE
        - RESTRUCTURE
      default: CREATE
