openapi: 3.0.3
info:
  description: TH1
  title: TH1
  version: 0.0.1

paths:
  /converter:
    post:
      operationId: convertTable
      parameters:
        - in: query
          name: mode
          required: false
          schema:
            default: CREATE
            enum:
              - CREATE
              - EXTEND
              - REPLACE
              - RESTRUCTURE
            type: string
      responses:
        "200":
          description: OK
